# Generated by Django 3.2.8 on 2021-11-08 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20211108_1148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
