# Generated by Django 3.2.8 on 2021-10-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_remove_prodect_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='address',
            field=models.TextField(max_length=333, null=True),
        ),
        migrations.AddField(
            model_name='custom',
            name='country',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='custom',
            name='dob',
            field=models.DateField(null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='custom',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='custom',
            name='state',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='custom',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='custom',
            name='profile_img',
            field=models.ImageField(blank=True, default='fz/assain/img/fz.jpg', upload_to='profile'),
        ),
    ]
