# Generated by Django 3.2.8 on 2021-10-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20211012_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom',
            name='profile_img',
        ),
    ]
