# Generated by Django 3.2.8 on 2021-10-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_remove_custom_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='dob',
            field=models.CharField(max_length=33, null=True, verbose_name='date of birth'),
        ),
    ]
