# Generated by Django 3.2.8 on 2021-10-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_alter_custom_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom',
            name='dob',
        ),
        migrations.AddField(
            model_name='custom',
            name='district',
            field=models.CharField(max_length=33, null=True),
        ),
    ]
