# Generated by Django 3.2.8 on 2021-10-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='profile_img',
            field=models.ImageField(blank=True, default='fz/assain/img/fz.jpg', null=True, upload_to='profile'),
        ),
    ]
