# Generated by Django 3.2.8 on 2021-10-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_custom_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodect',
            name='actual_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='prodect',
            name='offer',
            field=models.IntegerField(null=True),
        ),
    ]
