# Generated by Django 3.2.8 on 2021-11-05 10:03

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_alter_custom_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=333, unique=True)),
                ('brand_img', models.ImageField(blank=True, upload_to='fz/projects/img 1/prodect')),
                ('brand_discription', models.TextField(blank=django.db.models.fields.TextField, max_length=333)),
                ('brand_date', models.DateField(auto_now_add=True, max_length=333)),
            ],
        ),
    ]
