# Generated by Django 3.2.8 on 2021-11-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
